curl http://localhost:8080/api/v1/employees



####
curl http://localhost:8080/api/v1/employee/9c6f2c7b-b4e6-44c3-9c52-a97a7b2b72f1
###
curl http://localhost:8080/api/v1/employee/4bee3dd9-63c2-4c9e-a2ae-ddfa19fce8a



###
POST http://localhost:8080/api/v1/addEmployee HTTP/1.1
content-type: application/json

{
  "firstName":"Cristino" ,
  "lastName":"Ronaldo",
  "email":"roynaldo@gmail.com"
}


###
DELETE  http://localhost:8080/api/v1/employee/96f13235-6661-4136-9942-394925089593 HTTP/1.1





###
curl -X DELETE http://localhost:8080/api/v1/employee/60a17f54-8307-46c9-843a-133ce2cb89ab